// 47都道府県データ
// ja: 日本語表記, romaji: ローマ字表記（PT/EN用）

export const prefectures = [
  { ja: "北海道", romaji: "Hokkaido" },
  { ja: "青森県", romaji: "Aomori" },
  { ja: "岩手県", romaji: "Iwate" },
  { ja: "宮城県", romaji: "Miyagi" },
  { ja: "秋田県", romaji: "Akita" },
  { ja: "山形県", romaji: "Yamagata" },
  { ja: "福島県", romaji: "Fukushima" },
  { ja: "茨城県", romaji: "Ibaraki" },
  { ja: "栃木県", romaji: "Tochigi" },
  { ja: "群馬県", romaji: "Gunma" },
  { ja: "埼玉県", romaji: "Saitama" },
  { ja: "千葉県", romaji: "Chiba" },
  { ja: "東京都", romaji: "Tokyo" },
  { ja: "神奈川県", romaji: "Kanagawa" },
  { ja: "新潟県", romaji: "Niigata" },
  { ja: "富山県", romaji: "Toyama" },
  { ja: "石川県", romaji: "Ishikawa" },
  { ja: "福井県", romaji: "Fukui" },
  { ja: "山梨県", romaji: "Yamanashi" },
  { ja: "長野県", romaji: "Nagano" },
  { ja: "岐阜県", romaji: "Gifu" },
  { ja: "静岡県", romaji: "Shizuoka" },
  { ja: "愛知県", romaji: "Aichi" },
  { ja: "三重県", romaji: "Mie" },
  { ja: "滋賀県", romaji: "Shiga" },
  { ja: "京都府", romaji: "Kyoto" },
  { ja: "大阪府", romaji: "Osaka" },
  { ja: "兵庫県", romaji: "Hyogo" },
  { ja: "奈良県", romaji: "Nara" },
  { ja: "和歌山県", romaji: "Wakayama" },
  { ja: "鳥取県", romaji: "Tottori" },
  { ja: "島根県", romaji: "Shimane" },
  { ja: "岡山県", romaji: "Okayama" },
  { ja: "広島県", romaji: "Hiroshima" },
  { ja: "山口県", romaji: "Yamaguchi" },
  { ja: "徳島県", romaji: "Tokushima" },
  { ja: "香川県", romaji: "Kagawa" },
  { ja: "愛媛県", romaji: "Ehime" },
  { ja: "高知県", romaji: "Kochi" },
  { ja: "福岡県", romaji: "Fukuoka" },
  { ja: "佐賀県", romaji: "Saga" },
  { ja: "長崎県", romaji: "Nagasaki" },
  { ja: "熊本県", romaji: "Kumamoto" },
  { ja: "大分県", romaji: "Oita" },
  { ja: "宮崎県", romaji: "Miyazaki" },
  { ja: "鹿児島県", romaji: "Kagoshima" },
  { ja: "沖縄県", romaji: "Okinawa" },
] as const;

export type Prefecture = typeof prefectures[number];
